image: node:lts-alpine

definitions:
    steps:
        - step: &deps
              name: Install npm dependencies
              caches:
                  - node
              script:
                  - npm install
        - step: &checks
              name: Check Types/ESLint/Prettier
              caches:
                  - node
              script:
                  - npm run check
        - step: &build-and-push
            name: 'Docker build + push'
            image: python:3.9-alpine
            script:
              - pip3 install -U awscli

              - export BRANCH_TAG=$(echo "$BITBUCKET_BRANCH" | sed -E 's/([^0-9a-zA-Z]+)/-/g' | awk '{print tolower($0)}')
              - export REPO=$DOCKER_REPO_URL/kidsloop-auth-backend   # DOCKER_REPO_URL is workspace wide variable
              - export COMMIT_TAG=$(echo $BITBUCKET_COMMIT | cut -c1-7)
              - printf '"Git tag":"%s", "Git commit":"%s" "ECR repo":"%s"' $BRANCH_TAG $COMMIT_TAG $REPO

              - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin $DOCKER_REPO_URL

              - docker build -t kidsloop-auth-server .

              - docker tag kidsloop-auth-server:latest $REPO:$BRANCH_TAG
              - docker tag kidsloop-auth-server:latest $REPO:$BRANCH_TAG-latest
              - docker tag kidsloop-auth-server:latest $REPO:$BRANCH_TAG-$BITBUCKET_BUILD_NUMBER
              - docker tag kidsloop-auth-server:latest $REPO:$BRANCH_TAG-$COMMIT_TAG

              - docker push $REPO:$BRANCH_TAG
              - docker push $REPO:$BRANCH_TAG-latest
              - docker push $REPO:$BRANCH_TAG-$BITBUCKET_BUILD_NUMBER
              - docker push $REPO:$BRANCH_TAG-$COMMIT_TAG

            services:
              - docker

pipelines:
  default:
        - step: *deps
        - step: *checks
  branches:
      master:
        - step: *deps
        - step: *checks
        - step: *build-and-push

  custom:
      build-and-push:
        - step: *build-and-push
