apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  namespace: kidskube-local
spec:
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
      - name: auth-server
        env:
          - name: DATABASE_URL
            value: postgres://postgres:kidsloop@postgres1:5432/postgres1
          - name: DATABASE_LOGGING
            value: "true"
          - name: JWT_PRIVATE_KEY_FILENAME
            value: ./keys/auth_server.priv
          - name: JWT_PUBLIC_KEY_FILENAME
            value: ./keys/auth_server.pub
          - name: JWT_ISSUER
            value: kidsloop
          - name: JWT_ALGORITHM
            value: RS256
          - name: JWT_ACCESS_TOKEN_DURATION
            value: "900"
          - name: JWT_REFRESH_TOKEN_DURATION
            value: "1206000"
          - name: DOMAIN
            value: fe.alpha.kidsloop.net
          - name: PORT
            value: "8083"
          - name: ROUTE_PREFIX
            value: /auth-server
          - name: AMS_PUBLIC_KEY
            value: |
              -----BEGIN PUBLIC KEY-----
              the public key that you generated for auth-lambda-funcs.
              Look in the README to check out how this variable should be formatted.
              -----END PUBLIC KEY-----
        image: auth-server-tilt
        resources: {}
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
  namespace: kidskube-local
spec:
  selector:
    app: auth-server
  ports:
  - port: 8083
    targetPort: 8083

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-server-ingress
  namespace: kidskube-local
  annotations:
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/enable-cors: "true"
    kubernetes.io/ingress.class: "nginx"
    # cert-manager.io/issuer: "selfsigned"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
  - host: fe.alpha.kidsloop.net
    http:
      paths:
      - pathType: Prefix
        path: "/auth-server"
        backend:
          service:
            name: auth-server
            port:
              number: 8083
